### ISSUE TITLE
duplicate strain names

### ISSUE THREAD

**Issue by jasonsahl** [andrewsanchez/NCBI_tools#5]
I'm seeing some strain names that are duplicated. On 653:

/home/jsahl/database/all_bacteria_fastas/Peptoclostridium_difficile

Files like:

GCA_000009205.1_Peptoclostridium_difficile_630630_Complete_Genome.fna
GCA_000027105.1_Peptoclostridium_difficile_R20291R20291_Chromosome.fna

**Comment by andrewsanchez** [comment]
Running rename.py on /home/jsahl/database/all_bacteria_fastas/Peptoclostridium_difficile/ should fix that.  

The renaming code in rename.py is the same in sync.py, so I don't know why those duplicates showed up.

Working on separate script to download specific organisms, instead of all bacteria, so I can test and investigate these odd cases more efficiently.

**Comment by jasonsahl** [comment]
I also see the following problem:
GCA_001267045.1_Clostridium_botulinum58752_CD_Scaffold.fna

With no space between the species and strain names

**Comment by andrewsanchez** [comment]
Working on some regular expressions that will fix these.

**Comment by andrewsanchez** [comment]
How does /home/asanchez/scratch/newnames.txt look?

```bash
asanchez@bio653:~$ grep "_sp_\|_sub_\|_subsp_\|strain" scratch/newnames.txt | wc -l
0
asanchez@bio653:~$ grep "GCA_001267045.1" /home/asanchez/scratch/newnames.txt
GCA_001267045.1_Clostridium_botulinum_58752_CD_Scaffold.fna
asanchez@bio653:~$ grep "GCA_000009205.1" /home/asanchez/scratch/newnames.txt
GCA_000009205.1_Peptoclostridium_difficile_630_Complete_Genome.fna
asanchez@bio653:~$ grep "GCA_000027105.1" /home/asanchez/scratch/newnames.txt
```

**Comment by jasonsahl** [comment]
Looks pretty good to me, thanks!

**Comment by andrewsanchez** [comment]
Great, let me know if you spot any other bugs.  Just pushed the lastest rename.py.  You can get that and run `python rename.py ncbi_data/bacteria_fastas/`
